WebTDi/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static
from .views import gallery_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('tribe/', include('home.urls')),
    path('district/', include('district_wise.urls')),
    path('accounts/', include('accounts.urls')),
    path('gallery/',gallery_view, name='gallery'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('tribe-form/', tribe_form_view, name='tribe_form'),
    path('<slug>/pdf/', tribe_pdf_view, name='tribe_pdf'),
    path('<name>/<year>/', tribe_detail_view, name='tribe_detail'), 
    path('test/', test_view, name='test'),
     path('download-template/', download_template, name='download_template'),
]

home/models.py
from django.db import models
from django.db.models import Sum
from django.core.cache import cache
from django.utils.text import slugify
from django.utils import timezone

from django.contrib.auth import get_user_model
User = get_user_model()

from django.conf import settings


# Create your models here.

class Tribe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tribe',default=settings.ADMIN_USER_PHONE_NUMBER)
    year = models.IntegerField()
    name = models.CharField(max_length=50)
    total_tribals = models.IntegerField(null=True, blank=True)
    H_DI = models.FloatField(null=True, blank=True)
    E_DI = models.FloatField(null=True, blank=True)
    S_DI = models.FloatField(null=True, blank=True)
    C_DI = models.FloatField(null=True, blank=True)
    G_DI = models.FloatField(null=True, blank=True)
    tribal_incidence = models.FloatField(null=True, blank=True)
    tribal_intensity = models.FloatField(null=True, blank=True)
    TDI = models.FloatField(null=True, blank=True)
    UNC_CD_score= models.FloatField(null=True, blank=True)
    UNC_IM_score= models.FloatField(null=True, blank=True)
    UNC_MC_score= models.FloatField(null=True, blank=True)
    UNC_CM_score= models.FloatField(null=True, blank=True)
    UNC_FS_score= models.FloatField(null=True, blank=True)
    UNC_LE_score= models.FloatField(null=True, blank=True)
    UNC_DRO_score= models.FloatField(null=True, blank=True)
    UNC_IC_score= models.FloatField(null=True, blank=True)
    UNC_OW_score= models.FloatField(null=True, blank=True)
    UNC_SANI_score= models.FloatField(null=True, blank=True)
    UNC_FUEL_score= models.FloatField(null=True, blank=True)
    UNC_DRWA_score= models.FloatField(null=True, blank=True)
    UNC_ELECTR_score= models.FloatField(null=True, blank=True)
    UNC_ASS_score= models.FloatField(null=True, blank=True)
    UNC_LAN_score= models.FloatField(null=True, blank=True)
    UNC_ARTS_score= models.FloatField(null=True, blank=True)
    UNC_EV_score= models.FloatField(null=True, blank=True)
    UNC_MEET_score= models.FloatField(null=True, blank=True)

    CEN_CD_score= models.FloatField(null=True, blank=True)
    CEN_IM_score= models.FloatField(null=True, blank=True)
    CEN_MC_score= models.FloatField(null=True, blank=True)
    CEN_CM_score= models.FloatField(null=True, blank=True)
    CEN_FS_score= models.FloatField(null=True, blank=True)
    CEN_LE_score= models.FloatField(null=True, blank=True)
    CEN_DRO_score= models.FloatField(null=True, blank=True)
    CEN_IC_score= models.FloatField(null=True, blank=True)
    CEN_OW_score= models.FloatField(null=True, blank=True)
    CEN_SANI_score= models.FloatField(null=True, blank=True)
    CEN_FUEL_score= models.FloatField(null=True, blank=True)
    CEN_DRWA_score= models.FloatField(null=True, blank=True)
    CEN_ELECTR_score= models.FloatField(null=True, blank=True)
    CEN_ASS_score= models.FloatField(null=True, blank=True)
    CEN_LAN_score= models.FloatField(null=True, blank=True)
    CEN_ARTS_score= models.FloatField(null=True, blank=True)
    CEN_EV_score= models.FloatField(null=True, blank=True)
    CEN_MEET_score= models.FloatField(null=True, blank=True)

    CD_contri_to_H= models.FloatField(null=True, blank=True)
    IM_contri_to_H= models.FloatField(null=True, blank=True)
    MC_contri_to_H= models.FloatField(null=True, blank=True)
    CM_contri_to_H= models.FloatField(null=True, blank=True)
    FS_contri_to_H= models.FloatField(null=True, blank=True)

    LE_contri_to_E= models.FloatField(null=True, blank=True)
    DRO_contri_to_E= models.FloatField(null=True, blank=True)

    IC_contri_to_S= models.FloatField(null=True, blank=True)
    OW_contri_to_S= models.FloatField(null=True, blank=True)
    SANI_contri_to_S= models.FloatField(null=True, blank=True)
    FUEL_contri_to_S= models.FloatField(null=True, blank=True)
    DRWA_contri_to_S= models.FloatField(null=True, blank=True)
    ELECTR_contri_to_S= models.FloatField(null=True, blank=True)
    ASS_contri_to_S= models.FloatField(null=True, blank=True)

    LAN_contri_to_C= models.FloatField(null=True, blank=True)
    ARTS_contri_to_C= models.FloatField(null=True, blank=True)

    EV_contri_to_G= models.FloatField(null=True, blank=True)
    MEET_contri_to_G= models.FloatField(null=True, blank=True)

    H_contri_to_TDI= models.FloatField(null=True, blank=True)
    E_contri_to_TDI= models.FloatField(null=True, blank=True)
    S_contri_to_TDI= models.FloatField(null=True, blank=True)
    C_contri_to_TDI= models.FloatField(null=True, blank=True)
    G_contri_to_TDI= models.FloatField(null=True, blank=True)


    village_details = models.JSONField(null=True, blank=True)

    class Meta:
        unique_together = ('user', 'year', 'name')


    def save(self, *args, **kwargs):
        # self.slug = slugify(self.name)
        super(Tribe, self).save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.name}-{self.year}-{self.id}"
    


class Tribe_Image(models.Model):
    tribe = models.ForeignKey(Tribe, on_delete=models.SET_NULL, related_name='tribe_image', null=True, blank=True)
    logo_image=models.ImageField(upload_to='images/logo_images')
    main_image=models.ImageField(upload_to='images/main_images')
    main_desc = models.CharField(max_length=100,null=True, blank=True)
    village_image=models.ImageField(upload_to='images/village_images')
    village_desc = models.CharField(max_length=100,null=True, blank=True)
    location=models.CharField(max_length=50, null=True, blank=True)
    map_image = models.ImageField(upload_to='images/map_images')
    date = models.DateField(null=True, blank=True)

    # def __str__(self):
    #     return f"{self.tribe.name} images"

    
class Report_Excel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='excel_report')
    year = models.IntegerField()
    file = models.FileField(upload_to='user_excel_reports/')

templates/form/district_form.html
{% extends 'base.html' %}

{% block content %}

<style>
  body {
    font-family: 'Arial', sans-serif;
  }

  .messages {
    list-style: none;
    padding: 10px;
    margin: 0;
    border: 1px solid #ccc;
    background-color: #f0f0f0;
    color: #333;
  }

  .messages li {
    margin-bottom: 5px;
    padding: 5px;
    border: 1px solid #ddd;
    background-color: #fff;
  }

  .messages .error {
    color: #d9534f;
    background-color: #f2dede;
    border-color: #ebccd1;
  }

  form {
    max-width: 600px;
    margin: 20px auto;
  }

  label {
    display: block;
    margin-bottom: 5px;
  }

  input,
  select {
    width: 100%;
    padding: 8px;
    margin-bottom: 15px;
    box-sizing: border-box;
  }

  .file_upload_box {
    margin-bottom: 15px;
  }

  #formset {
    margin-bottom: 15px;
  }

  #form {
    border: 1px solid #ddd;
    padding: 10px;
    margin-bottom: 10px;
  }

  #add-form,
  #remove-form {
    background-color: #4caf50;
    color: #fff;
    padding: 10px;
    cursor: pointer;
  }

  button[type="submit"] {
    background-color: #337ab7;
    color: #fff;
    padding: 10px;
    cursor: pointer;
  }
</style>


{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ formset.management_form }}

  {% if district_form.errors %}
  <p style="color: red;">There were errors in the form. Please correct them.</p>
  {% endif %}

  <div>• Add the scores data of each District and find the Tribal Development Index of tribes in that particular
    District <br>• Note: All data for <b>all Districts</b> at <b>once</b></div><br>
  <hr><br>
  <label for="id_year">Year: </label>
  <span>* Enter the year carefully</span>
  <input type="number" name="year" step="any" id="id_year" required>

  <select id="entryType_dis" onchange="toggleForms()" required>
    <option value="" disabled selected hidden>-- Data Input Type</option>
    <option value="manual">Manual Entry</option>
    <option value="file">Upload Excel</option>
  </select>

  <div class="file_upload_box" id="dis_fileUpload_form" style="display: none;">
    <input type="file" name="district_excel_file" placeholder="Choose file">
  </div>

  <div id="district_manual_form" style="display: none;">
    <div id="formset">
      {% for form in formset %}
      <div id="form">
        <label for="id_form-0-name">Name:</label>
        <select name="form-0-name" id="id_form-0-name" fdprocessedid="isxhvk">
          {% for district in districts %}
          <option value="{{district.slug}}">{{district.slug}}</option>
          {% endfor %}
        </select>



        <p>
          <label for="id_form-0-st_population">St population:</label>
          <input type="number" name="form-0-st_population" step="any" id="id_form-0-st_population"
            fdprocessedid="glejfu">


        </p>


        <p>
          <label for="id_form-0-total_population">Total population:</label>
          <input type="number" name="form-0-total_population" step="any" id="id_form-0-total_population"
            fdprocessedid="2nu804">


        </p>


        <p>
          <label for="id_form-0-W_BMI">Women with BMI below normal score:</label>
          <input type="number" name="form-0-W_BMI" step="any" id="id_form-0-W_BMI" fdprocessedid="c0h97a">


        </p>


        <p>
          <label for="id_form-0-C_UW">Children Under weight score:</label>
          <input type="number" name="form-0-C_UW" step="any" id="id_form-0-C_UW" fdprocessedid="gb1gt">


        </p>


        <p>
          <label for="id_form-0-AN_W">Anaemia-Women score:</label>
          <input type="number" name="form-0-AN_W" step="any" id="id_form-0-AN_W" fdprocessedid="m73un">


        </p>


        <p>
          <label for="id_form-0-AN_C">Anaemia- children:</label>
          <input type="number" name="form-0-AN_C" step="any" id="id_form-0-AN_C" fdprocessedid="358vcq">


        </p>


        <p>
          <label for="id_form-0-AHC_ANC">Antenatal checkup 1st trimister:</label>
          <input type="number" name="form-0-AHC_ANC" step="any" id="id_form-0-AHC_ANC" fdprocessedid="wpwaq9">


        </p>


        <p>
          <label for="id_form-0-AHC_Full_ANC">Full Antenatal care score:</label>
          <input type="number" name="form-0-AHC_Full_ANC" step="any" id="id_form-0-AHC_Full_ANC" fdprocessedid="csaf3m">


        </p>


        <p>
          <label for="id_form-0-AHC_PNC">Post natal care score:</label>
          <input type="number" name="form-0-AHC_PNC" step="any" id="id_form-0-AHC_PNC" fdprocessedid="9iy313j">


        </p>


        <p>
          <label for="id_form-0-AHC_HI">Health Insurance score:</label>
          <input type="number" name="form-0-AHC_HI" step="any" id="id_form-0-AHC_HI" fdprocessedid="9t9wc2">


        </p>


        <p>
          <label for="id_form-0-Enrollment">ST Enrollment score:</label>
          <input type="number" name="form-0-Enrollment" step="any" id="id_form-0-Enrollment" fdprocessedid="mk8n8a">


        </p>


        <p>
          <label for="id_form-0-Equity">Equity Outcome score:</label>
          <input type="number" name="form-0-Equity" step="any" id="id_form-0-Equity" fdprocessedid="cr2mf8">


        </p>


        <p>
          <label for="id_form-0-E_DropRate">Drop out score:</label>
          <input type="number" name="form-0-E_DropRate" step="any" id="id_form-0-E_DropRate" fdprocessedid="zy0fv">


        </p>


        <p>
          <label for="id_form-0-S_Sani">Sanitation score:</label>
          <input type="number" name="form-0-S_Sani" step="any" id="id_form-0-S_Sani" fdprocessedid="nki0g">


        </p>


        <p>
          <label for="id_form-0-S_CoFu">Source of Cooking Fuel score:</label>
          <input type="number" name="form-0-S_CoFu" step="any" id="id_form-0-S_CoFu" fdprocessedid="w2sqd9">


        </p>


        <p>
          <label for="id_form-0-S_DrWa">Source of Drinking water score:</label>
          <input type="number" name="form-0-S_DrWa" step="any" id="id_form-0-S_DrWa" fdprocessedid="984vzc">


        </p>


        <p>
          <label for="id_form-0-S_Elec">Electricity score:</label>
          <input type="number" name="form-0-S_Elec" step="any" id="id_form-0-S_Elec" fdprocessedid="9c6rpp">


        </p>


        <p>
          <label for="id_form-0-DELETE">Delete:</label>
          <input type="checkbox" name="form-0-DELETE" id="id_form-0-DELETE">




        </p>
        <button type="button" id="add-form">Add Form</button>
        <button type="button" id="remove-form">Remove Last Form</button>
      </div>
      {% endfor %}
    </div>
  </div>

 

  <input type="submit" value="Submit">
</form>
<script>
  // When the "Add Form" button is clicked
  document.getElementById('add-form').addEventListener('click', function () {
    // Get the div containing the form elements
    var formsetDiv = document.getElementById('formset');

    // Get the last form in the formset
    var lastForm = formsetDiv.lastElementChild;

    // Clone the last form
    var newForm = lastForm.cloneNode(true);

    // Clear values in the cloned form
    newForm.querySelectorAll('input, select, textarea').forEach(function (element) {
      element.value = '';
    });

    // Increment the form index
    var formCountField = document.getElementById('id_form-TOTAL_FORMS');
    var newFormIndex = parseInt(formCountField.value);
    newFormIndex++;
    formCountField.value = newFormIndex;

    // Update the IDs of form fields in the cloned form
    newForm.querySelectorAll('[id]').forEach(function (element) {
      element.id = element.id.replace(/-\d+/, '-' + (newFormIndex - 1));
    });

    // Update the names of form fields in the cloned form
    newForm.querySelectorAll('[name]').forEach(function (element) {
      element.name = element.name.replace(/-\d+/, '-' + (newFormIndex - 1));
    });
    newForm.querySelectorAll('label').forEach(function (label) {
      var labelFor = label.getAttribute('for');
      if (labelFor) {
        label.setAttribute('for', labelFor.replace(/-\d+/, '-' + (newFormIndex - 1)));
      }
    });
    // Append the new form to the formset
    formsetDiv.appendChild(newForm);
  });

  document.getElementById('remove-form').addEventListener('click', function () {
    var formsetDiv = document.getElementById('formset');

    if (formsetDiv.childElementCount > 1) {
      var lastForm = formsetDiv.lastElementChild;
      var deleteCheckbox = lastForm.querySelector('[id$="-DELETE"]');

      if (deleteCheckbox) {
        if (deleteCheckbox.checked) {
          // Hide the form and disable its inputs
          lastForm.style.display = 'none';
          lastForm.querySelectorAll('input, select, textarea').forEach(function (element) {
            element.disabled = true;
          });
        } else {
          // If not marked for deletion, set the DELETE field to true
          deleteCheckbox.checked = true;
        }
      }
    }
  });


  function toggleForms() {
    var entryType = document.getElementById("entryType_dis").value;
    var manualForm = document.getElementById("district_manual_form");
    var fileUploadForm = document.getElementById("dis_fileUpload_form");
    // var slugSelect = document.getElementById("id_form-0-tribeID");


    if (entryType === "manual") {
      manualForm.style.display = "block";
      fileUploadForm.style.display = "none";
      // slugSelect.setAttribute("required", "required");
    } else if (entryType === "file") {
      manualForm.style.display = "none";
      fileUploadForm.style.display = "block";
      // slugSelect.removeAttribute("required");
    }
  }


</script>

{% endblock content %}

templates/form/tribe_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  <div class="download-container">
    <p>
      Download the empty Excel template with column headers:
      <a href="{% url 'download_template' %}" class="download-link">Download Template</a>
    </p>
    <p class="instructions">Fill in the data in the downloaded file and upload it using the form below:</p>
  </div>

  <div class="important-note">
    <strong>Note:</strong> It is important to fill in the data in the above-given template.
  </div>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form }}
    <label for="id_year">Select Year:</label>
    <input type="number" name="year" step="any" id="id_year" required placeholder="Year">

    <div class="file_upload_box" id="HH_fileUpload_form">
      <input type="file" name="households_excel_file" placeholder="Upload excel file" required>
    </div>

    <hr>

    <button type="submit" class="tribe_form_submit">Submit</button>
  </form>
</div>



  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }
  
    .container {
      max-width: 800px;
      margin: 20px auto;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      padding: 20px;
    }
  
    .download-container {
      text-align: center;
      margin-bottom: 20px;
      background-color: #f8d7da; /* Red background color for emphasis */
      padding: 10px;
      border-radius: 5px;
      border: 1px solid #f5c6cb; /* Border color to highlight */
    }
  
    .download-link {
      display: inline-block;
      padding: 10px 20px;
      background-color: #dc3545; /* Dark red background color for the link */
      color: white;
      text-decoration: none;
      font-size: 18px;
      border-radius: 5px;
      transition: background-color 0.3s;
    }
  
    .download-link:hover {
      background-color: #c82333; /* Slightly darker red on hover */
    }
  
    .important-note {
      color: #721c24; /* Dark red color for the important note */
      background-color: #f8d7da; /* Light red background color */
      border: 1px solid #f5c6cb; /* Border color to match download container */
      padding: 10px;
      border-radius: 5px;
      margin-top: 20px;
    }
  
    .instructions {
      margin-top: 10px;
      font-size: 14px;
      color: #666;
    }
  
    form {
      margin-top: 20px;
    }
  
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
  
    input[type="number"],
    input[type="file"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      box-sizing: border-box;
    }
  
    hr {
      border: none;
      border-top: 1px solid #ddd;
      margin: 20px 0;
    }
  
    .tribe_form_submit {
      background-color: #008CBA;
      color: white;
      padding: 10px 20px;
      font-size: 16px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      transition: background-color 0.3s;
    }
  
    .tribe_form_submit:hover {
      background-color: #007AA5;
    }
  </style>
  

{% endblock content %}