WebTDi/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static
from .views import gallery_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('tribe/', include('home.urls')),
    path('district/', include('district_wise.urls')),
    path('accounts/', include('accounts.urls')),
    path('gallery/',gallery_view, name='gallery'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/urls.py
from django.urls import path
from .views import *


urlpatterns = [

    path('register/',register_view,name='register'),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit', profile_edit_view, name='profile_edit'),
    path('download/<int:file_id>/', download_excel, name='download_excel'),

]

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('tribe-form/', tribe_form_view, name='tribe_form'),
    path('<slug>/pdf/', tribe_pdf_view, name='tribe_pdf'),
    path('<name>/<year>/', tribe_detail_view, name='tribe_detail'), 
    path('test/', test_view, name='test'),
     path('download-template/', download_template, name='download_template'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager
from django import forms

class Profile(AbstractUser):

    username = None
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, unique=True)
    profile_pic = models.ImageField(upload_to='images/profile_images', blank=True, null=True)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']
    objects = UserManager()

    def __str__(self):
        return self.email
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.forms import UserChangeForm

class ProfileCreationForm(UserCreationForm):
    phone_number = forms.IntegerField(required=True)
    email = forms.EmailField(required=True)
    profile_pic = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2', 'profile_pic']

    def save(self, commit=True):
        profile = super().save(commit=False)

        # Handle the profile picture
        if 'profile_pic' in self.cleaned_data:
            profile.profile_pic = self.cleaned_data['profile_pic']

        if commit:
            profile.save()

        return profile
    

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'profile_pic']

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        # Pre-fill the form with the current data from the instance
        if self.instance:
            self.initial['first_name'] = self.instance.first_name
            self.initial['last_name'] = self.instance.last_name
            self.initial['email'] = self.instance.email
            self.initial['phone_number'] = self.instance.phone_number

accounts/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.contrib.auth.forms import UserChangeForm
from .models import Profile
from .forms import ProfileUpdateForm
from home.models import Report_Excel

from django.contrib import messages
# Create your views here.
from .forms import *
from django.contrib.auth import get_user_model
User = get_user_model()
from django.conf import settings
from home.models import Tribe, Report_Excel
from district_wise.models import District
from django.shortcuts import get_object_or_404
from mimetypes import guess_type


def register_view(request):
    if request.method == "POST":
        form = ProfileCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password1']
            user = authenticate(request, phone_number=phone_number, password=password)
            login(request, user)
            messages.success(request, 'Registration successful')
            return redirect('home')
        else:
            # Include form errors in the context
            context = {
                'form': form,
            }
            # Display error messages using Django messages framework
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        form = ProfileCreationForm()
        context = {
            'form': form,
        }

    return render(request, 'accounts/register.html', context)




def login_view(request):
    context = {}
    if request.method == "POST":
        phone_number = request.POST.get('phone_number')
        password = request.POST.get('password')

        user = authenticate(request, phone_number=phone_number, password=password)
        if user is None:
            messages.error(request, 'Invalid Phone Number or Password')
            return render(request, 'accounts/login.html', context=context)
        login(request, user)
        messages.success(request, 'Successfully logged in')
        return redirect('/')
    
    return render(request, 'accounts/login.html', context=context)

def logout_view(request):
    if request.method == "POST":
        logout(request)
        messages.success(request, 'Successfully logged out')
        return redirect('login')
    
    return render(request, 'accounts/logout.html')


def profile_view(request):
    user = User.objects.get(phone_number=settings.ADMIN_USER_PHONE_NUMBER)
    tribes = Tribe.objects.filter(user = user, year='2022')
    districts=District.objects.filter(user = user, year='2022')
    profile = request.user
    
    excel_files = Report_Excel.objects.filter(user=profile)
    

    if request.method == 'POST':
      
        form = ProfileCreationForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            
            return redirect('accounts/profile.html')
        else:
            print(form.errors)
        
    context = {
        'profile' :profile,
        'tribes' : tribes,
        'districts' :districts,
        'excel_files': excel_files
    }
    return render (request, 'accounts/profile.html',context)

@login_required
def profile_edit_view(request):
    # Get the user's profile instance using the phone_number
    profile_instance, created = Profile.objects.get_or_create(phone_number=request.user.phone_number)
    print(profile_instance)
    print(profile_instance.first_name)
    print(profile_instance.last_name)
    print(profile_instance.email)
    print(profile_instance.phone_number)
    if request.method == 'POST':
        # Create an instance of the ProfileUpdateForm with the user's data
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile_instance)
        print(form)
        if form.is_valid():
            # Save the form data to update the profile
            form.save()

            # Redirect to the profile page or any other page you want
            return redirect('profile')  # Change 'profile' to the actual name of your profile page

    else:
        # If it's a GET request, initialize the form with the current user's data
        form = ProfileUpdateForm(instance=profile_instance)

    context = {
        'form': form,
    }
    return render(request, 'accounts/editprofile.html', context)



def download_excel(request, file_id):
    excel_file = get_object_or_404(Report_Excel, id=file_id)
    file_path = excel_file.file.path
    content_type, encoding = guess_type(file_path)
    response = HttpResponse(content_type=content_type)
    response['Content-Disposition'] = f'attachment; filename="{excel_file.file.name}"'
    with open(file_path, 'rb') as file:
        response.write(file.read())
    return response

templates/accounts/editprofile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Update Profile</title>
  <link rel="stylesheet" href="{% static 'newcss/globalregister.css' %}" />
  <link rel="stylesheet" href="{% static 'newcss/register.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600;700&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap" />

  <style>
    .frame-wrapper {
      height: 402px;
    }

    .frame-group {
      border-radius: 51.44px;
      border: 2px solid #FFE5B4;
    }
  </style>
</head>


<body>
  {% if messages %} {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} {% endif %}

  <div class="frame-parent">
    <div class="frame-group">
      <div class="main-logo-parent">
        <div class="main-logo">
          <b class="tdi-webtool"><a href="{% url 'home' %}">TDI Webtool</a></b>
        </div>
        <div class="sign-up-parent">
          <div class="sign-up">Update Profile</div>
        </div>

        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="frame-container">
            <div class="iconamoonprofile-fill-parent">
              <i class="fa-solid fa-user"></i>
              <div class="firstname-wrapper">{{ form.first_name }}</div>
            </div>
            <div class="iconamoonprofile-fill-parent">
              <i class="fa-solid fa-user"></i>
              <div class="firstname-wrapper">{{ form.last_name }}</div>
            </div>
            <div>
              <button type="submit" class="login-btn">Update Profile</button>
            </div>
          </div>

        </form>


      </div>
      <div class="frame-wrapper">
        <div class="home-parent">
          <b class="home"><a href="{% url 'home' %}">HOME</a></b>
          <b class="home"><a href="#">RESEARCH</a></b>
          <b class="home"><a href="#">TEAM</a></b>
          <b class="home"><a href="#">GALLERY</a></b>
          <b class="home"><a href="#">ABOUT US</a></b>
          <b class="home"><a href="#">CONTACT US</a></b>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, width=device-width" />

  <link rel="stylesheet" href="{% static 'newcss/globallogin.css' %}" />
  <link rel="stylesheet" href="{% static 'newcss/login.css' %}" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700&display=swap" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://code.jquery.com/jquery-3.6.0.slim.js">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js">
  </script>
  <style>
    /* Customize the alert styles */
    .alert-warning {
      background-color: #fff3cd;
      border-color: #ffeeba;
      color: #856404;
    }

    /* Style the close button */
    .alert-warning .close {
      color: #856404;
    }

    /* Style the close button on hover */
    .alert-warning .close:hover {
      color: #6c757d;
    }

    /* Style the close button icon */
    .alert-warning .close span {
      font-size: 20px;
    }

    /* Style the close button icon on hover */
    .alert-warning .close span:hover {
      opacity: 0.8;
    }
  </style>
</head>

<body>
  {% if messages %} {% for message in messages %}

  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} {% endif %}
  <div class="frame-parent">
    <div class="frame-child"></div>
    <div class="frame-group">
      <div class="main-logo-parent">
        <div class="main-logo">
          <b class="tdi-webtool"><a href="{% url 'home' %}">TDI Webtool</a></b>
        </div>
        <div class="log-in-parent">
          <div class="log-in">Log In</div>
          <div class="please-enter-your">Please enter your details</div>
        </div>

        <div style="width: 100%;">
          {% if not request.user.is_authenticated %}
          <form method="POST" class="frame-container">
            {% csrf_token %}


            <div class="input-container">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Phone Number" name="phone_number">
            </div>

            <div class="input-container">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password">
            </div>

        </div>
        <div style=" width: 100%;">
          <button type="submit" class="login-btn">
            <div class="login">Login</div>
          </button>
        </div>
        </form>


        {% else %}
        <div class="accounts-head" style="text-align: center">
          You've Already logged in <b>{{user.username}}</b>. Do you
          want to <a href="{% url 'logout' %}">Logout</a> ?
        </div>
        {% endif %}
        <div class="already-have-an-account-parent">
          <div class="already-have-an">Don't have an account?</div>
          <div class="sign-in"><a href="{% url 'register' %}">Sign Up</a></div>
        </div>
        <!-- <div class="frame-div">
          <div class="social-media-icons">
            <i class="fa-brands fa-square-instagram"></i>
          </div>
          <div class="social-media-icons">
            <i class="fa-brands fa-youtube"></i>
          </div>
          <div class="social-media-icons">
            <i class="fa-brands fa-linkedin"></i>
          </div>

        </div> -->
      </div>
      <div class="frame-wrapper">
        <div class="home-parent">
          <b class="home"><a href="{% url 'home' %}">HOME</a></b>
          <b class="home"><a href="#">RESEARCH</a></b>
          <b class="home"><a href="#">TEAM</a></b>
          <b class="home"><a href="#">GALLERY</a></b>
          <b class="home"><a href="#">ABOUT US</a></b>
          <b class="home"><a href="#">CONTACT US</a></b>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/accounts/logout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, width=device-width" />
  <link rel="stylesheet" href="{% static 'newcss/globallogout.css' %}" />
  <link rel="stylesheet" href="{% static 'newcss/logout.css' %}" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@600;700&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" />
</head>
<script src="https://code.jquery.com/jquery-3.6.0.slim.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>

<body>
  {% if messages %} {% for message in messages %}

  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} {% endif %}
  <div class="frame-parent">
    {% if request.user.is_authenticated %}
    <div class="frame-group">
      <form method="POST">
        {% csrf_token %}
        <div class="frame-child"></div>
        <div class="frame-wrapper">
          <div class="confirm-logout-parent">
            <b class="confirm-logout">Confirm logout</b>
            <div class="frame-item"></div>
            <div class="are-you-sure">Are you sure you want to log out?</div>
            <div class="login-btn-parent">
              <div class="login-btn1" style="
                    background-color: white;
                    color: black;
                    border: 1px solid #000000db;
                  ">
                <div class="cancel">
                  <a href="{% url 'home' %}">Cancel</a>
                </div>
              </div>
              <div>
                <button class="login-btn1" style="border: none; background-color: #ffa018;" type="submit">
                  Ok
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>

    {% else %}
    <div class="accountsbox">
      <div class="accounts-head">
        <h2>You are already logged out.</h2>
      </div>
      <p>Click Here to <a href="{% url 'login' %}">login</a></p>
    </div>
    {% endif %}
  </div>
</body>

</html>

templates/accounts/profile.html
{% extends 'base.html' %} {% block content %} {% load static %}
<style>
  .login-btn {
    background-color: var(--color-white);
    color: var(--bs-dark);
  }

  .home:hover {
    color: var(--bs-dark);
  }

  #tribeDropdown:hover,
  #districtDropdown:hover {
    transform: none;
    color: var(--bs-dark);
  }
</style>

<div class="profile-child"></div>

<div class="frame-parent22-profile">
  <div class="profile-image-frame">
    {% csrf_token %}
    <label for="id_profile_pic">
      <img class="frame-child26-profile" alt=""
        src="{% if profile.profile_pic %}{{ profile.profile_pic.url }}{% else %}{% static 'images/profile_images/default-profile-pic.png' %}{% endif %}" />
    </label>
    <input type="file" name="profile_pic" id="id_profile_pic" style="display: none" />
  </div>

  <b class="profile-name-head">{{profile.first_name}}</b>
  <div class="frame-parent23-profile">
    <div class="my-account-profile-parent-profile">
      <div class="my-account-profile">My Account</div>
      <div class="login-btn3">
        <div class="logout">SETTINGS</div>
      </div>

      <div class="login-btn3">
        <div class="edit"><a href={% url 'profile_edit' %}>Edit</a></div>
      </div>
    </div>
    <div class="frame-parent24-profile">
      <div class="user-information-parent">
        <b class="user-information">User Information</b>
        <div class="frame-parent25-profile">
          <div class="frame-parent26-profile">
            <div class="full-name-parent-profile">
              <div class="profile-credential-head">FULL NAME</div>
              <div class="profile-credential-box">
                <div class="profile-credential">
                  {{profile.first_name}} {{profile.last_name}}
                </div>
              </div>
            </div>
            <div class="full-name-parent-profile">
              <div class="profile-credential-head">EMAIl</div>
              <div class="profile-credential-box">
                <div class="profile-credential">{{profile.email}}</div>
              </div>
            </div>
          </div>
          <div class="frame-parent26-profile">
            <div class="full-name-parent-profile">
              <div class="profile-credential-head">PHONE NUMBER</div>
              <div class="profile-credential-box">
                <div class="profile-credential">{{profile.phone_number}}</div>
              </div>
            </div>
            <div class="full-name-parent-profile">
              <div class="profile-credential-head">AGE</div>
              <div class="profile-credential-box">
                <div class="profile-credential">20</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="user-information-parent">
        <b class="user-information">MY DATA</b>
        <div class="frame-parent28-profile">
          <div class="frame-parent29-profile">
            <div class="tribe-wise-data-profile-wrapper-profile">

              <div class="tribe-wise-data-profile" id="profile-tribe-Dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  My Data
                </a>

                <ul class="dropdown-menu custom-dropdown">
                  {% for file in excel_files %}
                  <li>
                    {{ file.year }} - <a href="{% url 'download_excel' file.id %}">Download</a>
                  </li>
                  {% endfor %}

                </ul>
              </div>


            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/register.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, width=device-width" />

  <link rel="stylesheet" href="{% static 'newcss/globallogin.css' %}" />
  <link rel="stylesheet" href="{% static 'newcss/register.css' %}" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700&display=swap" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://code.jquery.com/jquery-3.6.0.slim.js">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js">
  </script>
  <style>
    /* Customize the alert styles */
    .alert-warning {
      background-color: #fff3cd;
      border-color: #ffeeba;
      color: #856404;
    }

    /* Style the close button */
    .alert-warning .close {
      color: #856404;
    }

    /* Style the close button on hover */
    .alert-warning .close:hover {
      color: #6c757d;
    }

    /* Style the close button icon */
    .alert-warning .close span {
      font-size: 20px;
    }

    /* Style the close button icon on hover */
    .alert-warning .close span:hover {
      opacity: 0.8;
    }
  </style>
</head>

<body>
  {% if messages %} {% for message in messages %}

  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} {% endif %}
  <div class="frame-parent">
    <div class="frame-child"></div>
    <div class="frame-group">
      <div class="main-logo-parent">
        <div class="main-logo">
          <b class="tdi-webtool"><a href="{% url 'home' %}">TDI Webtool</a></b>
        </div>
        <div class="log-in-parent">
          <div class="log-in">Sign Up</div>
          <div class="please-enter-your">Please enter your details</div>
        </div>

        <div style="width: 100%;">
          {% if not request.user.is_authenticated %}
          <form method="POST" class="frame-container">
            {% csrf_token %}


            <div class="input-container">
              <i class="fa-solid fa-user"></i>
              <input type="text" placeholder="First Name" name="first_name">
            </div>
            <div class="input-container">
              <i class="fa-solid fa-user"></i>
              <input type="text" placeholder="Last Name" name="last_name">
            </div>
            <div class="input-container">
              <i class="fa-solid fa-envelope"></i>
              <input type="email" placeholder="Email" name="email">
            </div>
            <div class="input-container">
              <i class="fa-solid fa-phone"></i>
              <input type="number" placeholder="Phone Number" name="phone_number">
            </div>

            <div class="input-container">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password1">
            </div>
            <div class="input-container">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Confirm Password" name="password2">
            </div>

        </div>
        <div style=" width: 100%;">
          <button type="submit" class="login-btn">
            <div class="login">Register</div>
          </button>
        </div>
        </form>



        {% endif %}
        <div class="already-have-an-account-parent">
          <div class="already-have-an">Already have an account?</div>
          <div class="sign-in"><a href="{% url 'login' %}">Sign In</a></div>
        </div>

      </div>
      <div class="frame-wrapper">
        <div class="home-parent">
          <b class="home"><a href="{% url 'home' %}">HOME</a></b>
          <b class="home"><a href="#">RESEARCH</a></b>
          <b class="home"><a href="#">TEAM</a></b>
          <b class="home"><a href="#">GALLERY</a></b>
          <b class="home"><a href="#">ABOUT US</a></b>
          <b class="home"><a href="#">CONTACT US</a></b>
        </div>
      </div>
    </div>
  </div>
</body>

</html>